### ISSUE TITLE
Launching a widget after swiping up for home has a 5 second delay

### ISSUE THREAD

**Issue by trygveaa** [termux/termux-widget#40]
**Problem description**

If you use gestures navigation and try to launch a widget after swiping up to go home, it takes 5 seconds before Termux appears.

**Steps to reproduce**

1. Use Android 10 and make sure it's set to use gesture navigation
2. Open any app. (I don't think it matters which app you open, it happens for me with all I've tested, including Chrome and Termux itself.)
3. Swipe up to go to the home screen.
4. Click on the widget to launch it.

**Expected behavior**

Termux should launch immediately, like it does when you use button navigation.

**Additional information**

* Termux application version: Built from master (commit b943e8a of widget and 9b7c710 of app), but I'm pretty sure it happens for the released versions as well.
* Android OS version: 10
* Device model: Pixel 3

**Comment by trygveaa** [comment]
I found these posts which talk about the issue. However, the workaround with using a pending intent doesn't seem to work anymore.
https://stackoverflow.com/questions/5600084/starting-an-activity-from-a-service-after-home-button-pressed-without-the-5-seco
http://www.programmersought.com/article/9497587349/
https://www.b4x.com/android/forum/threads/delay-when-startactivity-is-used-when-app-is-paused-by-home-key.105658/

**Comment by RalfWerner** [comment]
@trygveaa This issue is already 8 months old and you may have already solved the problem! I can _**not**_ repeat it, but have another device: S610 (Samsung Pad Galaxy Tab S6 Lite) and a slightly _**different problem.**_ To your 4 **reproduction steps:**
1. There are two gesture setups (1/3 lines below) that work slightly differently and for the 2nd is a sensitivity slider.
2. Open the app: _Setup_ (top in shot) and _files_ and both in _PiP_, where termux is also included in the _hidden app box._ 
3. _Swipe_ between start and task screen is problem-free in _both_ setups, but not necessary because of PiP.
4. Click on _Widget:_ `ls env ps` opens termux here _in Picture_. Then widget _and_ Termux are on the start screen.

![grafik](https://user-images.githubusercontent.com/45426380/100345924-57ad7800-2fe3-11eb-894c-40e565f9b8dc.png)
_PiP_ is not necessary for the _Swipe_ effect, but for the _Delay_ problem describe in the [Widget: reference](https://github.com/RalfWerner/integrated-process/issues/2#issuecomment-733700709). The _**first tap**_ in _Widget_ open _Termux-in-Picture_ (when PiP-Box is closed) and all following or when PiP-Box is open (top/right in shot) "stacked" as described.
![grafik](https://user-images.githubusercontent.com/45426380/100351739-369d5500-2fec-11eb-995b-d75ec4055de8.png)
Many taps in _Widget_ lead to many _**open**_ shells in _Termux._ Here 21 are displayed, but they only become active with `crtl+n`. If you _know the effect_ you can live with it. In the three shots above the actions on _extra keys_ are described on _extra keys_.

**Comment by trygveaa** [comment]
This is fixed in version 0.113 of termux-app, after allowing Termux to draw over other apps 🎉 (not sure exactly which version fixed it).

@RalfWerner: That sounds like a separate issue, so you may want to open another issue for that. I'm closing this one, since my issue is fixed.

**Comment by RalfWerner** [comment]
@trygveaa thanks for feedback
> allowing Termux to draw over other apps

Is a _new_ setting in Android 11 (default before). So everybody use Widget has to set it and has to _kown the needing of it!_

**Comment by trygveaa** [comment]
> Is a _new_ setting in Android 11 (default before). So everybody use Widget has to set it and has to _known the needing of it!_

I was asked by Termux to enable it, so I didn't need to have prior knowledge of it.

> You have also discussed with @agnostic-apollo the OS-KB theme too (separate than here in the Issues 2011,2014).
> I did this in [1995 ff](https://github.com/termux/termux-app/issues) and will check his last commit too.

The OS-KB theme? I'm not sure what theme you are referring to.

> The property `hide-soft-keyboard-on-startup=true` was inserted in the 113 version for hiding the OS-KB at start. Probably we have different wishes to the behavior. I want to avoid the frequent unwanted shopping, as it is rarely necessary on the device with _in Picture View_ and deliberately attended with `KB` Key Toggles.

What do you mean by "unwanted shopping"?

And I'm not sure I see the relation between this issue and the keyboard stuff?

**Comment by RalfWerner** [comment]
> I was asked by Termux to enable it, so I didn't need to have prior knowledge of it.

True! One time, in a short notification for 3 seconds and with knowledge of the Steps in Android settings in your language you can do it. In the case "Update Android to 11 and start termux" it could be easily overlooked. Open the Android-Dialog (also needed for storage access), when related data (here `~/shortcuts`) exist, is more clearly.
> The OS-KB theme? I'm not sure what theme you are referring to.

OS-KB=On Screen KeyBoard! [reference](https://github.com/termux/termux-app/pull/1953#issuecomment-817907932) and [here](https://github.com/termux/termux-app/pull/2114#issuecomment-855899147) and some other.
> What do you mean by "unwanted shopping"? And I'm not sure I see the relation between this issue and the keyboard stuff?

Sorry not  "shopping" - wrong word supplement "Showing (OS-KB)" was meaned and - of course not this (widget) issue!

**Comment by trygveaa** [comment]
> True! One time, in a short notification for 3 seconds and with knowledge of the Steps in Android settings in your language you can do it. In the case "Update Android to 11 and start termux" it could be easily overlooked. Open the Android-Dialog (also needed for storage access), when related data (here `~/shortcuts`) exist, is more clearly.

I thought I got a modal asking to enable it last time, but if I disable it now I just get a toast that says I need to enable it. Either way, it was clear enough for me, but maybe it can be improved.

> OS-KB=On Screen KeyBoard! [reference](https://github.com/termux/termux-app/pull/1953#issuecomment-817907932) and [here](https://github.com/termux/termux-app/pull/2114#issuecomment-855899147) and some other.

I understood that OS-KB is on screen keyboard, but what do you mean with "theme"? There is no theme mentioned in either of those references. But now that I read it again, maybe you meant "thing", as in we were discussing the keyboard?

> Sorry not "shopping" - wrong word supplement "Showing (OS-KB)" was meaned and - of course not this (widget) issue!

Okay, not sure when it shows up unwanted for you. For me it is when the keyboard was closed and I return to Termux after unlocking the screen or switching back from another application. As discussed in #2114 it seems like the enable/disable option is the only way to prevent this.

**Comment by RalfWerner** [comment]
> I thought I got a **modal asking to enable** it last time ... but maybe it **can be improved**.

**That** would be great! I had already asked @agnostic-apollo, but he means the _three seconds bubble_ is sufficient. I would also be pleased with a workaround in `.bashrc` something like `[ -d ~/.shortcuts ]&& am broadcast ...` as I do with `! -d storage`
> but what do you mean with "theme ... maybe you meant "thing"

Right "theme=thing"! **Widget** (here) is _one_ theme and **Keybord** is _another_ thing and should discuss [there](https://github.com/termux/termux-app/pull/2114#issuecomment-855899147)
