### ISSUE TITLE
The following command needs to be continuosly run in the termux in background

### ISSUE THREAD

**Issue by Dhruvkanani** [termux/termux-widget#46]
tmux new hping3 --flood -2 ip -p port
The above command works perfectly in termux but when i am trying to execute it using termux widget this command is  not executed.

**Comment by xeffyr** [comment]
Follow https://wiki.termux.com/wiki/Termux:Widget:

1. Install Termux:Widget add-on.
2. Create a script ~/.shortcuts/hping3.sh with PROPER!!! shebang:
   ```
   #!/data/data/com.termux/files/usr/bin/sh
   tmux new -d hping3 --flood -2 ip -p port
   ```
3. `chmod +x ~/.shortcuts/hping3.sh`

**Comment by Dhruvkanani** [comment]
Sir the problem is that the command is executed and termux closes immediately which is of no use. Actually i need that the attack should remain continue in background but this not happening.

**Comment by xeffyr** [comment]
> Sir the problem is that the command is executed and termux closes immediately which is of no use. 

`tmux new -d {your command here}` will create a tmux instance running in background - as you requested. Yes, Termux:Widget will exit but `tmux` will continue to run. Note that Termux must have wake lock enabled or have at least one session opened, otherwise Android will terminate your processes.

Also, make sure your command is written properly.

**Comment by Dhruvkanani** [comment]
I followed your guidance but when I tried it and then write tmux ls command in termux it shows no server running. I had also turned on wakelock but still no tmux session was running
