### ISSUE TITLE
Failed to install on Oxygen OS Android 11

### ISSUE THREAD

**Issue by rushic24** [termux/termux-widget#51]
Could you please recompile it for my device

Thanks

**Comment by Grimler91** [comment]
I can only guess what the problem is, but probably you are trying to install termux apps from different sources.

You need to install the termux-app and all addon apps from the same source, i.e. either only google play, or only f-droid. 

F-droid is the recommended installation source as the apps on google play cannot be updated and hence are outdated.

See also https://github.com/termux/termux-app#installation
