### ISSUE TITLE
nodemon

### ISSUE THREAD

**Issue by mnemo9** [termux/termux-widget#53]
when using a `Termux:Widget` shortcut to run a shell script that runs `nodemon` the following error is shown:

    /data/data/com.termux/files/home/.shortcuts/script1:4: /data/data/com.termux/files/usr/bin/nodemon: bad interpreter: /usr/bin/env: no such file or directory
    
    [Process completed (code 127) - press Enter]

`termux-exec` is installed and I also tried adding `export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so` in the script right after the shebang line which I also fixed using `termux-fix-shebang`

**Comment by Grimler91** [comment]
What is `nodemon`? What does that script contain? It is probably running some other script which has `#!/usr/bin/env` as shebang. 

Unfortunately termux-exec is not active for widget scripts, since it is run from the widget app without env vars like LD_PRELOAD set, so it won't fix any shebangs on the fly.

**Comment by xeffyr** [comment]
That's exactly issue with shebang. It is not possible to use `#!/usr/bin/env` and in generally every path beginning with FHS paths in Termux:Widget and other add-ons running a shell not initialized through (`$PREFIX/bin/login`).

Solution is to execute `termux-fix-shebang` on this script:
```
termux-fix-shebang $PREFIX/bin/nodemon
```

So you need to fix not the just shortcut but everything that is being executed as its child process. `LD_PRELOAD` takes effect only for spawned processed.

This **will not work** because `execve` is not hooked.
```
export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
/data/data/com.termux/files/usr/bin/nodemon
```

This will work:
```
export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
bash -c "exec /data/data/com.termux/files/usr/bin/nodemon"
```

**Comment by xsro** [comment]
Maybe we can use following command to fix it too.

```sh
node $(which nodemon) 
```

**Comment by fazle-rabbi-dev** [comment]
> Maybe we can use following command as a workaround.
> 
> ```shell
> node $(which nodemon) 
> ```

Wow 😲  Thanks for this 🎉🥳
