### ISSUE TITLE
No files in ~/.shortcuts

### ISSUE THREAD

**Issue by Sepero** [termux/termux-widget#58]
Latest release v0.13 no longer appears to see files in ~/. shortcuts

The widget displays "No files in ~/. shortcuts"

After uninstalling and reinstalling v0.12, everything working again as before.

* Termux application version: 0.117
* Android OS version: 10
* Device model: OnePlus 6

**Comment by agnostic-apollo** [comment]
Related to #57. `~/.shortcuts` must be a directory and not a symlink. Create a symlink under it for now. Support for `~/.termux/widget` directory will be added later.

**Comment by Sepero** [comment]
Understood

Will support for symbolic link be brought back? I need to use a symbolic link because I keep the true directory in a separate location with other directories for keeping regular backups. Thank you

**Comment by agnostic-apollo** [comment]
You will have to keep the true directory either under `~/.termux` or `~/.shortcuts` directory even in future, that won't change. The canonical path must be under either of those, even if a symlink. You can always run `rsync` command to sync the files to some external directory before backup.

**Comment by Sepero** [comment]
I also use the same backup procedure with the `~/.termux` directory. I use a symlink for `~/.termux`. Is there a technical reason for not being able to support symlink for `~/.shortcuts`?

Since the future location will be based as `~/.termux/shortcuts`, then this could make my backup process simpler. I could have the true directory under the symlink'd ~/.termux` directory. I assume that wouldn't be an issue?

I appreciate your help.

**Comment by agnostic-apollo** [comment]
>Is there a technical reason for not being able to support symlink for ~/.shortcuts

It might be possible to allow `~/.shortcuts` to be a symlink to a directory under `~/.termux` but that will require more code to be added and more checks. However, I don't specially see any reason for supporting that if a user can select any directory under `~/.termux` directly anyways. No point in making code more complex.

> I could have the true directory under the symlink'd ~/.termux directory. 

If your true directory would be under `~/.termux`, you won't need to play around with symlinks anyways since support can be added for custom directory, with the default to be `~/.termux/widget`. Then you can just backup entire `~/.termux`. FYI, all this likely won't be done anytime soon though.
