### ISSUE TITLE
[Assistant] Widgets can't be added to Home Launcher (long press home/assistant)

### ISSUE THREAD

**Issue by ZaneHannanAU** [termux/termux-widget#62]
Unsure if this is a recent change, but previously, I was able to add widgets to Home Launcher (see: ![T2](https://i.imgur.com/Lmdcqxr.png)), however, now that they don't work, I'm unable to add new ones as they just get redirected to the home screen (KISS):

https://gfycat.com/easybonyarmednylonshrimp ([direct video](https://giant.gfycat.com/EasyBonyArmednylonshrimp.mp4))

I'm not sure as to why this change was made. It's not a change to HL ([it hasn't been touched in 6 years](https://f-droid.org/packages/com.dynamicg.homebuttonlauncher)), but does affect how I'm able to use it.

**Comment by RalfWerner** [comment]
Two pictures from your [video](https://giant.gfycat.com/EasyBonyArmednylonshrimp.mp4) of second 5 and 6. What would you expect to do with SLHD?
![grafik](https://user-images.githubusercontent.com/45426380/141271571-5f01d923-f6e3-4443-9540-ea52a39125be.png)

**Comment by agnostic-apollo** [comment]
The `v0.113` made changes to how shortcuts were created and pinned shortcuts were directly sent to the default launcher instead of the calling app. I plan on changing behaviour for both [pinned and static shortcuts](https://github.com/termux/termux-widget/blob/v0.13.0/app/src/main/java/com/termux/widget/TermuxCreateShortcutActivity.java#L118), also mentioned [here](https://github.com/termux/termux-widget/issues/60#issuecomment-949946338).

https://github.com/termux/termux-widget/releases

**Comment by ZaneHannanAU** [comment]
@agnostic-apollo thank you, that'll resolve it I believe.
