### ISSUE TITLE
How to hide specific dirs/files in .shortcut and .shortcut/tasks

### ISSUE THREAD

**Issue by laoyur** [termux/termux-widget#77]
Hi, I created python scripts files in `.shortcut` dir:

```
~/.shortcuts/tasks $ ls -l
total 40
-rwx------ 1 u0_a458 u0_a458 4120 May  2 16:37 myscript.py
-rwx------ 1 u0_a458 u0_a458  228 Apr 18 00:21 myutil.py
```

`myscript.py` is my main script, and I run it from `Termux-Widget`

`myutil.py` is the module file which can be imported from `myscript.py`

My questions:

1.  How to hide `myutil.py`, which is not supposed to run directly from `Termux-Widget`, it should be hidden
2. After I run `myscript.py`,  a file called `__pycache__/myutil.cpython310.pyc` is created automatically, which should also be hidden from the `Termux-Widget` GUI

Is there any solution? Thank you guys.

**Comment by Grimler91** [comment]
You could move your module to one of the folders in `PYTHONPATH`, seen with `python3 -c "import sys; print(sys.path)"`, and then in myscript.py have something like `from mymodule.myutil import foo` or similar.

Could also put myutil.py somewhere else and import it using its absolute path, as outlined in https://stackoverflow.com/a/67692

Could also modify the `PYTHONPATH` env var to add the path to your myutil script, but since termux-widget doesn't run in a login shell it won't source profile scripts or your .bashrc, which would otherwise typically be where you would set that var

__pycache__ creation can be disabled with env var `PYTHONDONTWRITEBYTECODE` or by setting `sys.dont_write_bytecode`, outlined in https://stackoverflow.com/a/154617
