### ISSUE TITLE
launcher icon does not hide itself

### ISSUE THREAD

**Issue by rwtallant13** [termux/termux-widget#89]
When clicking the box to hide the icon the app closes but the icon never goes away. When trying to interact with it again it just opens to the app settings. 

Pixel 6 & Pixel 7, android 13, default pixel launcher.

**Comment by danijelcamdzic** [comment]
I believe this is no longer possible since Android 10. The app tries to dynamically change the visibility of the app icon by using:

```java
packageManager.setComponentEnabledSetting(componentName, state ? PackageManager.COMPONENT_ENABLED_STATE_ENABLED :PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
```

which no longer works. 

I too hate seeing an app icon which does nothing but take you to the settings when clicked so I removed the:

```xml
<category android:name="android.intent.category.LAUNCHER
```

from the `AndroidManifest.xml` file and rebuilt the app for myself. It now stays hidden as other `Termux` apps.

**Comment by agnostic-apollo** [comment]
Issue is with Pixel Launcher, if you disable launcher activity component, it replaces it with a shortcut that launches the app info activity in Android Settings for the app. For nova launcher, launcher icon does not show at all after disabling. Tested in Android 14 avd. Closing since not a Termux issue, report issue to respective launcher devs. 

```
com.google.android.apps.nexuslauncher  D  removing items from db . Reason: [removed because the corresponding package or component is removed. mOp=2 removedPackages=[] removedComponents=[{com.termux.widget/com.termux.widget.activities.TermuxWidgetActivity}]]
com.google.android.apps.nexuslauncher  D  Main / start: startAppShortcutOrInfoActivity
system_server I START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.termux.widget/android.app.AppDetailsActivity bnds=[781,1552][1022,1880]} with LAUNCH_MULTIPLE from uid 10159 (BAL_ALLOW_ALLOWLISTED_COMPONENT) result code=0
```
